### ISSUE TITLE
Using this with repos hosted on organizations

### ISSUE THREAD

**Issue by istx25** [pierredavidbelanger/githubappcaster#2]
Hi there! Thanks for putting this together.

Quoting your documentation: 

>Where generated-name-123456 is the name of your newly deployed app, and your_project is the name of any repository that belongs to you (the username entered earlier into the GITHUB_API_LOGIN variable).

(Bottom of https://elements.heroku.com/buttons/pierredavidbelanger/githubappcaster)

Is it possible to use this with GitHub repos that are hosted by an organization not a personal user? Do you have any recommendations for this? If not, what would be needed to adapt and I can make the changes?

Thanks!

**Comment by pierredavidbelanger** [comment]
Thank you for your interest in this projet!

Its a good idea, unfortunately this project pretty much assume one want to publish a [repo under a personal login username here](https://github.com/pierredavidbelanger/githubappcaster/blob/e1d99db74e40b236cb88d943c8779bc806b38c2d/src/main/java/ca/pjer/githubappcaster/App.java#L99).

I guess to adapt this project to use organisation, one need to [keep the auth env variables as is](https://github.com/pierredavidbelanger/githubappcaster/blob/e1d99db74e40b236cb88d943c8779bc806b38c2d/src/main/java/ca/pjer/githubappcaster/App.java#L149). And introduce a new **optional** env variable that controls [the path where to look for the repo](https://github.com/pierredavidbelanger/githubappcaster/blob/e1d99db74e40b236cb88d943c8779bc806b38c2d/src/main/java/ca/pjer/githubappcaster/App.java#L99).

It should be be that hard. The hardest part though would be to try to keep back compatibility (ie: when one does NOT have the new env var).

**Comment by istx25** [comment]
Thank you for the explanation. I don't really know Java but I'll make an attempt at it in a fork! :)

**Comment by pierredavidbelanger** [comment]
I could give it a go , if you are willing to test it .

**Comment by istx25** [comment]
If you're willing, that would be amazing. I'm more than happy to test it.

**Comment by istx25** [comment]
Also, PS we're both in Montreal! Small world!

**Comment by pierredavidbelanger** [comment]
I pushed something .

You can try the [Deploy to Heroku button on my feature branch](https://github.com/pierredavidbelanger/githubappcaster/tree/feature_organization#quick-deploy-with-the-heroku-button).

There is a new var `GITHUB_REPO_PREFIX` to allow entering an organisation name.

**Comment by istx25** [comment]
Okay awesome! I'll try this probably early next week. Still need to get the project setup. THANK YOU

**Comment by pierredavidbelanger** [comment]
No problem, take your time; Ill leave this issue open then. Thank you!

**Comment by istx25** [comment]
I've not been feeling well all this week so didn't get around to it yet but hope to soon. Thanks!

**Comment by pierredavidbelanger** [comment]
Really there should be absolutely no stress about this issue, stay well, the branch will wait.

**Comment by istx25** [comment]
Wow the time has gone by - I'm so sorry! I'm going to be looking at this in the next couple days. Thanks so much!

**Comment by istx25** [comment]
Sparkle isn't ready for our project as it's a Mac Catalyst project. I've tried implementing the beta features that were suggested by folks but I was unable to get it to work so we are going to come back once Sparkle has support for Mac Catalyst/sandboxed applications.

**Comment by pierredavidbelanger** [comment]
Oh, indeed, I've never tried Mac Catalyst, but I am not surprised Sparkle does not supports this use case yet.

I will still leave this issue open, so someone else (or you in the future) may test this feature someday.

Good luck!
